#!/bin/sh

echo "Executando build antes do push..."
npm run build

# Verifica se o build foi bem-sucedido
if [ $? -ne 0 ]; then
  echo "Erro no build. Push cancelado."
  exit 1
fi

# Adiciona a pasta dist ao commit atual
git add dist

# Verifica se há alterações na pasta dist para commitar
if git diff --cached --name-only | grep -q "dist/"; then
  git commit -m "Build: atualização automática da pasta dist" --no-verify
  echo "Pasta dist atualizada e commitada automaticamente."
fi

echo "Build concluído com sucesso. Continuando com o push..."
exit 0 